// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcqfxdKEGz7_LxWagtGCaqiKtPuzfdCDw',
    appId: '1:859656184348:web:b3a4677456de6475bdf5d9',
    messagingSenderId: '859656184348',
    projectId: 'studybuddy-224a6',
    authDomain: 'studybuddy-224a6.firebaseapp.com',
    storageBucket: 'studybuddy-224a6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1trC8hxj66EHXCo18YcAu8xE2POLz1Gk',
    appId: '1:859656184348:android:994833dc713b0237bdf5d9',
    messagingSenderId: '859656184348',
    projectId: 'studybuddy-224a6',
    storageBucket: 'studybuddy-224a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYx_y8scOUjL1zCNsoWHzyAfjW3V9z9rI',
    appId: '1:859656184348:ios:05fc15112bbcbe3fbdf5d9',
    messagingSenderId: '859656184348',
    projectId: 'studybuddy-224a6',
    storageBucket: 'studybuddy-224a6.firebasestorage.app',
    iosBundleId: 'com.example.studybuddy.studyBuddy',
  );
}
